### ISSUE TITLE
The integration is not complete right?

### ISSUE THREAD

**Issue by set92** [MaterializeInc/metabase-materialize-driver#12]
I was trying it in the demo of chbench but I couldn't use X-Ray with the materialized tables that I created. I thought it was a problem of version, so I installed the last version of metabase `docker run -d -p 3000:3000 --name metabase metabase/metabase` (0.39.0.1) and then I added this driver (0.0.5) using the ip of the gateway of the materialized docker as host in the configuration of metabase.

With this it works, and I can do native queries, but if I go to settings - Data Model, I see the data model of direct connection to other databases and the example but the one of materialize is empty. The same if I try to use X-ray on any materialize view, and the same in the lower part of the main page, where it says "Our data" and I have Materialize but when I click it is empty.

So, is an error on my side or is that this plugin is not made to support all the features of metabase? There is someway to have this features added?

**Comment by JLDLaughlin** [comment]
Hi @set92, thanks for opening this issue! The Metabase driver was created when Materialize was less complete (specifically in terms of Postgres compatibility). You're totally right that it wasn't supporting all of the features!

The specific feature you mentioned (x-ray) was also [reported by another user this morning](https://github.com/MaterializeInc/metabase-materialize-driver/issues/13). This [change to our pgjdbc fork should fix it for you](https://github.com/MaterializeInc/pgjdbc/pull/9), if you refer to our [newest release](https://github.com/MaterializeInc/metabase-materialize-driver/releases/tag/v.0.0.7).

If there are other features that you find are missing, please mention them here!

**Comment by set92** [comment]
I just try the v0.0.7 and all works, data models in administration panel and x-ray, thank you. 😄 

Only thing that would be nice to change is to pin the latest release, or I'm not sure what's the problem but in main page https://github.com/MaterializeInc/metabase-materialize-driver in releases to the right it still appears the 0.0.5, I didn't knew there was a v0.0.6 because it didn't appear and in README.md - "Without docker" it mentions v0.0.5. Maybe it only needs for @quodlibetor to specify that the 0.0.7 is the latest release?

**Comment by JLDLaughlin** [comment]
Thank you for that feedback, @set92! I wasn't updating `latest` correctly, it's fixed now 😄
